services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - carcierge_db:/app
    environment:
      - DEFAULT_ADMIN_EMAIL=PartnerPluslogistics@gmail.com
      - DEFAULT_ADMIN_PASSWORD=Admin@123
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  carcierge_db:
